services:
  auth:
    container_name: todo_auth_pocketbase
    restart: unless-stopped
    build:
      context: ./packages/auth/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./packages/auth/pb_data:/pb/pb_data
